# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lee Hee Kyeong
title: Student, Hallym Univ.
email: ram1539@naver.com/lhk645901@gmail,com
# email_title: Email (Email title override)
phone: 010-xxxx-7690
# phone_title: Phone (Phone title override)
website: http://34.64.195.174:9999/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mmm5910
stackoverflow_username: "00000001"

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/my_face.JPG 
about_content: | # this will include new lines to allow paragraphs
  
  안녕하세요. 한림대학교에 재학 중인 이희경입니다.<br>
  현재  소프트웨어학부에서 공부하고 있으며, 현재에는 게임 개발을 목표로 공부하고 있습니다.<br>
  <mark>Python</mark> <mark>JAVA</mark> <mark>c/c++</mark> <br>
  <mark>UnityEngine</mark> <br>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Coupang logistics services
        sub_title: ICQA,IB
        caption: 2021.12~2022.02
        quote: >
        description: | # this will include new lines to allow paragraphs
          ICQA에서는 재고관리, IB에서는 상품입고와 진열을 했습니다. 
    content:
      - layout: left
        title : Naver
        sub_title : Data mining
        caption : 2020.06~2020.09
        quote : >
        description: 
          네이버에서 단기아르바이트로 머신러닝을 위한 데이터마이닝 작업을 한 경험이 있습니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Hallym University
        sub_title: 콘텐츠 it
        caption: 2020~현재
        quote: > 
        description: | # this will include new lines to allow paragraphs
          한림대학교 소프트웨어학부에 재학중이며 전공은 콘텐츠it, 부전공은 스마트iot입니다. 




  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      저의 취미는 독서와 영화감상입니다. <br>
      최근 개발과 관련된 재미있고 흥미로운 책을 읽었는데, 몇 가지 소개해보고자 합니다.<br>
      
      ![alt text](/images/just_for_fun_linux.jpg "book1")
      ![alt text](/images/learning_network_with_picture.jpg "book2")
      ![alt text](/images/clean_code.jpg "book3")

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
